[versions]
kotlinx-coroutines = "1.10.2"
kotlin-logging = "7.0.14"
junit-jupiter = "6.0.2"
slf4j-api = "2.0.17"

kover-plugin = "0.9.4"
ktlint-plugin = "14.0.1"
nexus-plugin = "2.0.0"
versions-plugin = "0.53.0"
testlogger-plugin = "4.0.0"

[libraries]
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }

[plugins]
build-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover-plugin" }
build-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
build-nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-plugin" }
build-versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
build-testlogger = { id = "com.adarshr.test-logger", version.ref = "testlogger-plugin" }
